### PR TITLE
Issue 12

### LINKED ISSUE #12: Antenna coordinates are invalid
This is what the array looks like...
image

### PR DESCRIPTION
**Pull request by bennahugo**
Closes #12 

This is an implementation of the proposed antenna position fix. Things definitely looks a lot better on a plot
image

@tmolteno @rubyvanrooyen @o-smirnov please advise? I'm unsure of the exact layout -- I presume the antenna coordinates
are the fitted coordinates relative to info dict lat lon alt? However it is anybody's guess which way the handedness were fitted.
We need somehow to establish that East and North is the right way here. I'm thinking regenerating UVW coordinates using CASA?

Note I had to put in a kludge to override the observatory name (you can specify e.g. "kat-7" to overrule the default)  -- until we can get the TARTs registered with JPL this is what we will need to do (or Tim's group will need to distribute special ephemeris which is a huge maintenance upkeep...)

### CODE REVIEW

**Comment by bennahugo** [comment]
No cigar.... the problem is I don't know what to trust though -- how sure are we about the original uvw coordinates?

image

**Comment by tmolteno** [comment]
These changes look excellent @bennahugo 

1. The antenna layout is visible in the TART telescope web interface (https://tart.elec.ac.nz/viewer/ and switching the API endpoint to Rhodes (in the viewer). This looks correct, but would depend on the coordinate frame.  
image
2. The TART operates in the local frame with uv coordinates relative to straight up, and it looks like the UV coordinates you have are flattened by projection 
3. The TART array is flat in the tangent plane to the TART location. So the x,y TART antenna positions will result in an x,y,z offset in the geodetic (WGS84) frame used by the ANTENNA table.  So the x,y,z positions of each antenna need to be transformed before adding to the array_centroid.

**Comment by tmolteno** [comment]
Have a look at https://docs.astropy.org/en/stable/api/astropy.coordinates.offset_by.html. This could be used to offset the array_centroid by the antenna positions in meters.

**Comment by tmolteno** [comment]
I have merged, and we can fix the offsets in another issue!

**Comment by tmolteno** [comment]
This has been addressed and closed in Issue #15. Antenna positions now match the online view!

**Comment by bennahugo** [comment]
Hmm ok yes I still don't believe this is correct -- the w direction is supposed to point do declination (which matches the zenethal angle in the equatorial frame. These coordinates clearly do not point to the same point on the sphere probably due to the offsets not being done correctly -- therefore the projected array appears flatter. I will try and redo this until we get a better match -- I fully trust the UVW coordinates coming out of casacore so it is a matter of getting the array configuration correct

**Pull request merged**
