### PR TITLE
Model predict from online API

### LINKED ISSUE #42: Add options to download GNSS positions from online API
Implemented. This is needed for these large HDF databases without GNSS source catalog attached.

I will PR soon. just testing it now

### PR DESCRIPTION
**Pull request by bennahugo**
Closes #42 
This adds in capability to download GNSS TLS from online API for prediction when going from h5 files @tmolteno as discussed

### CODE REVIEW

**Comment by bennahugo** [comment]
@tmolteno getting very decent results from CASA calibration. I think you may be having SNR issues in your calibration because it looks like noise -- when I combine solution intervals across timestamps with a basic model predicted at every timestep using this branch I am able to calibrate Rhodes data
Raw data:
image
Tim cal:
image
CASA 10s intervals:
image

**Comment by bennahugo** [comment]
I see GPS satellites moving about from Rhodes. Phase rotated movie inbound shortly

**Comment by bennahugo** [comment]
https://user-images.githubusercontent.com/7934586/205961110-575fe3a9-637b-4be6-a0d5-d7dc19b641c9.mp4

**Comment by tmolteno** [comment]
Looking good. Closes #42

**Pull request merged**
