### PR TITLE
Make no-phasing warning depend on observation length

### PR DESCRIPTION
**Pull request by bennahugo**
Alright @tmolteno here you go - the critical warning of not rephasing is now dependent
on how much you move (at the celestial equator) over the course of the observation. If it is
more than say 5% of the instrument resolution then the warning is printed otherwise for a very short,
or single dump snapshot it will not.

### CODE REVIEW

**Comment by bennahugo** [comment]
This also prints useful information for the unfamiliar user on what to pick for their resolution bacause we already have a bunch of TARTs in the field.

**Comment by bennahugo** [comment]
So for the NZ TART it will equate to about just over a minute of observation time before this warning starts to trigger. Probably about half that for the Rhodes TART

**Comment by bennahugo** [comment]
Alright as discussed offline the field names now follow twelveball J convention (not eightball as I mentioned -- the zeniths are a bit too close when named per interval -- this makes the field names overlap too much @tmolteno

**Review by tmolteno — APPROVED** [review]
Looks good.

**Pull request merged**
