### PR TITLE
Conformance issues MAIN,FIELD table

### PR DESCRIPTION
**Pull request by bennahugo**
Closes #9

- Fix memo 229 compliance on main table
- Fix field table incorrect phase dirs when multiple dumps are present
- Fix time and direction computation when multiple dumps are present
- Ensure SCAN boundary is set to the integration length (traditionally the tracking scan should be constant in phasing direction
- Ensure field id phase directions have correct foreign key in main table

Close but no cigar yet
```python
CASA <3>: go listobs
--------> go(listobs)
Executing:  listobs()

2022-10-18 13:22:48     INFO    listobs::::
2022-10-18 13:22:48     INFO    listobs::::+    ##########################################
2022-10-18 13:22:48     INFO    listobs::::+    ##### Begin Task: listobs            #####
2022-10-18 13:22:48     INFO    listobs::::     listobs(vis="tart.ms",selectdata=True,spw="",field="",antenna="",
2022-10-18 13:22:48     INFO    listobs::::+            uvrange="",timerange="",correlation="",scan="",intent="",
2022-10-18 13:22:48     INFO    listobs::::+            feed="",array="",observation="",verbose=True,listfile="",
2022-10-18 13:22:48     INFO    listobs::::+            listunfl=False,cachesize=50,overwrite=False)
2022-10-18 13:22:48     INFO    listobs::ms::summary    ================================================================================
2022-10-18 13:22:48     INFO    listobs::ms::summary+              MeasurementSet Name:  /home/hugo/workspace/tart.ms      MS Version 2
2022-10-18 13:22:48     INFO    listobs::ms::summary+   ================================================================================
2022-10-18 13:22:48     INFO    listobs::ms::summary+      Observer: Tim     Project:   
2022-10-18 13:22:48     INFO    listobs::ms::summary+   Observation: TART
2022-10-18 13:22:48     INFO    listobs::MSMetaData::_computeScanAndSubScanProperties   Computing scan and subscan properties...
2022-10-18 13:22:48     INFO    listobs::ms::summary    Data records: 16560       Total elapsed time = 61.4989 seconds
2022-10-18 13:22:48     INFO    listobs::ms::summary+      Observed from   18-Oct-2022/11:27:18.3   to   18-Oct-2022/11:28:19.8 (UTC)
2022-10-18 13:22:48     INFO    listobs::ms::summary
2022-10-18 13:22:48     INFO    listobs::ms::summary+      ObservationID = 0         ArrayID = 0
2022-10-18 13:22:48     INFO    listobs::ms::summary+     Date        Timerange (UTC)          Scan  FldId FieldName             nRows     SpwIds   Average Interval(s)    ScanIntent
2022-10-18 13:22:48     INFO    listobs::ms::summary+     18-Oct-2022/11:27:18.3 - 11:27:19.3     1      0 zenith_scan_1              276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:19.3 - 11:27:20.4     2      1 zenith_scan_2              276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:20.4 - 11:27:21.4     3      2 zenith_scan_3              276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:21.4 - 11:27:22.4     4      3 zenith_scan_4              276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:22.4 - 11:27:23.4     5      4 zenith_scan_5              276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:23.4 - 11:27:24.5     6      5 zenith_scan_6              276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:24.5 - 11:27:25.5     7      6 zenith_scan_7              276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:25.5 - 11:27:26.5     8      7 zenith_scan_8              276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:26.5 - 11:27:27.5     9      8 zenith_scan_9              276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:27.5 - 11:27:28.6    10      9 zenith_scan_10             276  [0]  [1.04] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:28.6 - 11:27:29.6    11     10 zenith_scan_11             276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:29.6 - 11:27:30.6    12     11 zenith_scan_12             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:30.6 - 11:27:31.6    13     12 zenith_scan_13             276  [0]  [1.01] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:31.6 - 11:27:32.7    14     13 zenith_scan_14             276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:32.7 - 11:27:33.7    15     14 zenith_scan_15             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:33.7 - 11:27:34.7    16     15 zenith_scan_16             276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:34.7 - 11:27:35.7    17     16 zenith_scan_17             276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:35.7 - 11:27:36.8    18     17 zenith_scan_18             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:36.8 - 11:27:37.8    19     18 zenith_scan_19             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:37.8 - 11:27:38.8    20     19 zenith_scan_20             276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:38.8 - 11:27:39.8    21     20 zenith_scan_21             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:39.8 - 11:27:40.9    22     21 zenith_scan_22             276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:40.9 - 11:27:41.9    23     22 zenith_scan_23             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:41.9 - 11:27:42.9    24     23 zenith_scan_24             276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:42.9 - 11:27:43.9    25     24 zenith_scan_25             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:43.9 - 11:27:45.0    26     25 zenith_scan_26             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:45.0 - 11:27:46.0    27     26 zenith_scan_27             276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:46.0 - 11:27:47.0    28     27 zenith_scan_28             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:47.0 - 11:27:48.0    29     28 zenith_scan_29             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:48.0 - 11:27:49.1    30     29 zenith_scan_30             276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:49.1 - 11:27:50.1    31     30 zenith_scan_31             276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:50.1 - 11:27:51.1    32     31 zenith_scan_32             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:51.1 - 11:27:52.1    33     32 zenith_scan_33             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:52.1 - 11:27:53.2    34     33 zenith_scan_34             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:53.2 - 11:27:54.2    35     34 zenith_scan_35             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:54.2 - 11:27:55.2    36     35 zenith_scan_36             276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:55.2 - 11:27:56.2    37     36 zenith_scan_37             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:56.2 - 11:27:57.3    38     37 zenith_scan_38             276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:57.3 - 11:27:58.3    39     38 zenith_scan_39             276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:58.3 - 11:27:59.3    40     39 zenith_scan_40             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:27:59.3 - 11:28:00.3    41     40 zenith_scan_41             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:28:00.3 - 11:28:01.4    42     41 zenith_scan_42             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:28:01.4 - 11:28:02.4    43     42 zenith_scan_43             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:28:02.4 - 11:28:03.4    44     43 zenith_scan_44             276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:28:03.4 - 11:28:04.4    45     44 zenith_scan_45             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:28:04.4 - 11:28:05.5    46     45 zenith_scan_46             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:28:05.5 - 11:28:06.5    47     46 zenith_scan_47             276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:28:06.5 - 11:28:07.5    48     47 zenith_scan_48             276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:28:07.5 - 11:28:08.5    49     48 zenith_scan_49             276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:28:08.5 - 11:28:09.6    50     49 zenith_scan_50             276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:28:09.6 - 11:28:10.6    51     50 zenith_scan_51             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:28:10.6 - 11:28:11.6    52     51 zenith_scan_52             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:28:11.6 - 11:28:12.6    53     52 zenith_scan_53             276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:28:12.6 - 11:28:13.7    54     53 zenith_scan_54             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:28:13.7 - 11:28:14.7    55     54 zenith_scan_55             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:28:14.7 - 11:28:15.7    56     55 zenith_scan_56             276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:28:15.7 - 11:28:16.7    57     56 zenith_scan_57             276  [0]  [1.03] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:28:16.7 - 11:28:17.8    58     57 zenith_scan_58             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:28:17.8 - 11:28:18.8    59     58 zenith_scan_59             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary+                 11:28:18.8 - 11:28:19.8    60     59 zenith_scan_60             276  [0]  [1.02] 
2022-10-18 13:22:48     INFO    listobs::ms::summary               (nRows = Total number of rows per scan) 
2022-10-18 13:22:48     INFO    listobs::ms::summary    Fields: 60
2022-10-18 13:22:48     INFO    listobs::ms::summary+     ID   Code Name                RA               Decl           Epoch        nRows
2022-10-18 13:22:48     INFO    listobs::ms::summary+     0         zenith_scan_1       14:59:43.024405 -33.13.49.21187 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     1         zenith_scan_2       14:59:44.052219 -33.13.49.23469 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     2         zenith_scan_3       14:59:45.085767 -33.13.49.25764 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     3         zenith_scan_4       14:59:46.112517 -33.13.49.28043 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     4         zenith_scan_5       14:59:47.139346 -33.13.49.30323 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     5         zenith_scan_6       14:59:48.162135 -33.13.49.32594 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     6         zenith_scan_7       14:59:49.193045 -33.13.49.34884 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     7         zenith_scan_8       14:59:50.210767 -33.13.49.37144 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     8         zenith_scan_9       14:59:51.237586 -33.13.49.39425 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     9         zenith_scan_10      14:59:52.264420 -33.13.49.41706 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     10        zenith_scan_11      14:59:53.302585 -33.13.49.44012 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     11        zenith_scan_12      14:59:54.333562 -33.13.49.46303 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     12        zenith_scan_13      14:59:55.359164 -33.13.49.48581 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     13        zenith_scan_14      14:59:56.370443 -33.13.49.50828 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     14        zenith_scan_15      14:59:57.398975 -33.13.49.53114 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     15        zenith_scan_16      14:59:58.424633 -33.13.49.55393 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     16        zenith_scan_17      14:59:59.459732 -33.13.49.57694 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     17        zenith_scan_18      15:00:00.486690 -33.13.49.59977 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     18        zenith_scan_19      15:00:01.509949 -33.13.49.62251 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     19        zenith_scan_20      15:00:02.535081 -33.13.49.64530 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     20        zenith_scan_21      15:00:03.563248 -33.13.49.66816 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     21        zenith_scan_22      15:00:04.588546 -33.13.49.69096 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     22        zenith_scan_23      15:00:05.623978 -33.13.49.71398 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     23        zenith_scan_24      15:00:06.645474 -33.13.49.73670 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     24        zenith_scan_25      15:00:07.677358 -33.13.49.75965 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     25        zenith_scan_26      15:00:08.702773 -33.13.49.78245 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     26        zenith_scan_27      15:00:09.720042 -33.13.49.80508 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     27        zenith_scan_28      15:00:10.754031 -33.13.49.82808 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     28        zenith_scan_29      15:00:11.779581 -33.13.49.85090 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     29        zenith_scan_30      15:00:12.804588 -33.13.49.87370 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     30        zenith_scan_31      15:00:13.834551 -33.13.49.89662 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     31        zenith_scan_32      15:00:14.864692 -33.13.49.91954 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     32        zenith_scan_33      15:00:15.883571 -33.13.49.94222 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     33        zenith_scan_34      15:00:16.908794 -33.13.49.96504 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     34        zenith_scan_35      15:00:17.935392 -33.13.49.98788 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     35        zenith_scan_36      15:00:18.959733 -33.13.50.01069 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     36        zenith_scan_37      15:00:19.995649 -33.13.50.03375 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     37        zenith_scan_38      15:00:21.020267 -33.13.50.05656 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     38        zenith_scan_39      15:00:22.047024 -33.13.50.07942 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     39        zenith_scan_40      15:00:23.074226 -33.13.50.10229 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     40        zenith_scan_41      15:00:24.099370 -33.13.50.12512 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     41        zenith_scan_42      15:00:25.125280 -33.13.50.14797 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     42        zenith_scan_43      15:00:26.150523 -33.13.50.17080 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     43        zenith_scan_44      15:00:27.170866 -33.13.50.19353 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     44        zenith_scan_45      15:00:28.205169 -33.13.50.21657 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     45        zenith_scan_46      15:00:29.229504 -33.13.50.23938 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     46        zenith_scan_47      15:00:30.253904 -33.13.50.26221 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     47        zenith_scan_48      15:00:31.287726 -33.13.50.28524 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     48        zenith_scan_49      15:00:32.318777 -33.13.50.30822 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     49        zenith_scan_50      15:00:33.345665 -33.13.50.33110 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     50        zenith_scan_51      15:00:34.375686 -33.13.50.35405 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     51        zenith_scan_52      15:00:35.395010 -33.13.50.37677 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     52        zenith_scan_53      15:00:36.416595 -33.13.50.39954 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     53        zenith_scan_54      15:00:37.452031 -33.13.50.42262 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     54        zenith_scan_55      15:00:38.477870 -33.13.50.44549 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     55        zenith_scan_56      15:00:39.495991 -33.13.50.46819 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     56        zenith_scan_57      15:00:40.527934 -33.13.50.49120 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     57        zenith_scan_58      15:00:41.557921 -33.13.50.51417 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     58        zenith_scan_59      15:00:42.579149 -33.13.50.53694 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary+     59        zenith_scan_60      15:00:43.601207 -33.13.50.55973 J2000          276
2022-10-18 13:22:48     INFO    listobs::ms::summary    Spectral Windows:  (1 unique spectral windows and 1 unique polarization setups)
2022-10-18 13:22:48     INFO    listobs::ms::summary+     SpwID  Name   #Chans   Frame   Ch0(MHz)  ChanWid(kHz)  TotBW(kHz) CtrFreq(MHz)  Corrs
2022-10-18 13:22:48     INFO    listobs::ms::summary+     0                 1   REST    1575.420      2500.000         0.0   1575.4200   RR
2022-10-18 13:22:48     INFO    listobs::ms::summary    The SOURCE table is empty: see the FIELD table
2022-10-18 13:22:48     SEVERE  listobs::ms::summary    Antennas: 24:
2022-10-18 13:22:48     SEVERE  listobs::ms::summary+     ID   Name  Station   Diam.    Long.         Lat.                Offset from array center (m)                ITRF Geocentric coordinates (m)        
2022-10-18 13:22:48     SEVERE  listobs::ms::summary+                                                                        East         North     Elevation               x               y               z
2022-10-18 13:22:48     SEVERE  listobs::ms::summary+   Exception Reported: Exception: Telescope TART is not recognized by CASA.
2022-10-18 13:22:48     SEVERE  listobs::ms::summary+   ... thrown by casacore::MPosition casacore::MSMetaData::getObservatoryPosition(casacore::uInt) const at File: ../../ms/MSOper/MSMetaData.cc, line: 3276
2022-10-18 13:22:48     SEVERE  listobs::::     *** Error *** Exception: Telescope TART is not recognized by CASA.
2022-10-18 13:22:48     SEVERE  listobs::::+    ... thrown by casacore::MPosition casacore::MSMetaData::getObservatoryPosition(casacore::uInt) const at File: ../../ms/MSOper/MSMetaData.cc, line: 3276
2022-10-18 13:22:48     INFO    listobs::::     ##### End Task: listobs              #####
2022-10-18 13:22:48     INFO    listobs::::+    ##########################################
```

### CODE REVIEW

**Comment by tmolteno** [comment]
Hi Ben. I've just pushed a fix to the TIME_CENTROID v0.2.1b5 while this was being created! Can you bring that in to this?

**Comment by bennahugo** [comment]
sure @tmolteno I will merge that in -- I'm kludging a bit

**Comment by bennahugo** [comment]
@tmolteno are you happy with the field relabeling though? I'm not going to be breaking your pipelines or something?
Technically each interval must have its own phase centre because we are not tracking so that the imaging centres will be correct (it is possible to rephase to create a higher SNR map if we keep proper track of the zenith coordinates

**Comment by tmolteno** [comment]
Go for it. No pipelines use the MS. They're written in Rust (for the web front end)

**Comment by bennahugo** [comment]
I will let you know once I have it playing with casa. I'm currently assuming that your data is time ordered (all baselines for every timestamp so that I can broadcast the time axis over row by repeating. Is this a valid assumption? @tmolteno

**Comment by tmolteno** [comment]
I've merged this because it is already much better than the earlier versions. Will hold off on tagging a new release until you're happy with it. Perhaps when the notebooks of @rubyvanrooyen are going.

**Comment by bennahugo** [comment]
ok the HDF5 files contain more than one timestamp (1s integration) which breaks the previous assumptions (json??) that was made. I still can't get casa to accept TART as an array after making changes

**Comment by tmolteno** [comment]
The HDF files contain 60 consecutive snapshots. Perhaps we can address the HDF5 input in another issue. It would be great to have this feature as they're a much more compact way to archive data than the JSON files. Issue #10

**Comment by tmolteno** [comment]
The problem with the telescope is discussed here. https://github.com/e-merlin/eMERLIN_CASA_pipeline/issues/30. I'm parsing it.

**Comment by bennahugo** [comment]
No this is in the casacore ephem data (hosted by NRAO and mirrored by ASTRON). It is not hardcoded per say as that https://github.com/e-merlin/eMERLIN_CASA_pipeline/issues/30 ticket mentions. 

However we need to request this to be added (need a valid GPS coordinate).

**Comment by tmolteno** [comment]
Oh that is not good. So when there are hundreds of TARTs we need to register every one?

**Comment by bennahugo** [comment]
Yea lets take this to the ticket I raised so we can put this PR to bed

**Pull request merged**
