### PR TITLE
Support concating multiple json into a single ms

### LINKED ISSUE #24: Concat multiple json into single ms
Successor to discussion in #16 but for the json component of it

### PR DESCRIPTION
**Pull request by bennahugo**
Closes #24 

Ok I've implemented more of the same but just for a batch of json files (each single dump as seemingly is the only mode currently supported @tmolteno 

In the verification test below the first was obtained with h5 files
Second is obtained with json after running ```tart_vis2json --vis ../NZ_2022_10_19/*.hdf ``` using 
the fixed branch https://github.com/tmolteno/tart_modules/pull/2
(producing 600 single timestamp json files) from a handful of h5 files

```
CASA <5>: tb.open("tart_ms_data2/tart.ms/")
Out[5]: True
CASA <6>: timeh5 = tb.getcol("TIME")
CASA <7>: fieldh5 = tb.getcol("FIELD_ID")
CASA <9>: scanh5 = tb.getcol("SCAN_NUMBER")
CASA <11>: datah5 = tb.getcol("DATA")
CASA <12>: tb.open("tart_ms_data_json/tart.ms/")
Out[12]: True
CASA <13>: timejson = tb.getcol("TIME")
CASA <14>: fieldjson = tb.getcol("FIELD_ID")
CASA <15>: scanjson = tb.getcol("SCAN_NUMBER")
CASA <16>: datajson = tb.getcol("DATA")
CASA <18>: all(timeh5 == timejson)
Out[18]: True
CASA <19>: all(fieldh5 == fieldjson)
Out[19]: True
CASA <20>: all(scanh5 == scanjson)
Out[20]: True
CASA <23>: (datah5 == datajson).all()
Out[23]: True
```

I'm happy this appears to be working (also fixed a few issues with my checks previously implemented for h5...)

### CODE REVIEW

**Comment by bennahugo** [comment]
Also passes the same for UVW coordinates
```
CASA <24>: tb.open("tart_ms_data2/tart.ms/")
Out[24]: True

CASA <25>: uvwh5 = tb.getcol("UVW")

CASA <26>: tb.open("tart_ms_data_json/tart.ms/")
Out[26]: True

CASA <27>: uvwjson = tb.getcol("UVW")

CASA <28>: (uvwh5 == uvwjson).all()
Out[28]: True
```

**Comment by bennahugo** [comment]
You can run this as ```tart2ms --json ../tart_data/NZ_2022_10_19_json/*.json -c --phase_center_policy dump --override_telescope_name 'kat-7' ```

**Review by tmolteno — COMMENTED** [review]
Looks good. Can you add a quick example to the README (or a shell script in a folder called examples?)

**Comment by bennahugo** [comment]
Bit stretched with meetings the entire morning. Will be able to get to this
and the rephasing sometime in the afternoon.

**Comment by bennahugo** [comment]
@tmolteno alright added some examples

If we do API changes we would need to update them a bit

**Pull request merged**
